data<- read.table("./household_power_consumption.txt", header = TRUE, sep=";", dec=".")
subdata <- subset(data, data$Date=="1/2/2007" | data$Date=="2/2/2007")
datetime<- strptime(paste(subdata$Date, subdata$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
GlobalActivePower<- as.numeric(as.character(subdata$Global_active_power))
GlobalReactivePower<- as.numeric(as.character(subdata$Global_reactive_power))
voltage<- as.numeric(as.character(subdata$Voltage))
submetering1<- as.numeric(subdata$Sub_metering_1)
submetering2<- as.numeric(subdata$Sub_metering_2)
submetering3<- as.numeric(subdata$Sub_metering_3)
png("plot4.png", width=480, height=480)
par(mfrow = c(2,2))
plot(datetime, voltage, type="scatter", xlab="datetime", ylabe="voltage")
plot(datetime, voltage, type="scatter", xlab="datetime", ylabe="voltage")
plot(datetime, submetering1, type="scatter", ylab="Energy Submetering", xlab="")
lines(datetime, submetering1, type="scatter", col="red")
lines(datetime, submetering2, type="scatter", col="blue")
legend("topright", c("Sub_metering1", "Sub_metering2", "Sub_metering3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="0")
plot(datetime, GlobalReactivePower, type="scatter", xlabe="datetime", ylab="Global_reactive_power")
dev.off()
