data<- read.table("./household_power_consumption.txt", header = TRUE, sep=";", dec=".")
subdata <- subset(data, data$Date=="1/2/2007" | data$Date=="2/2/2007")
datetime<- strptime(paste(subdata$Date, subdata$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
GlobalActivePower<- as.numeric(as.character(subdata$Global_active_power))
submetering1<- as.numeric(subdata$Sub_metering_1)
submetering2<- as.numeric(subdata$Sub_metering_2)
submetering3<- as.numeric(subdata$Sub_metering_3)
png("plot3.png", width=480, height=480)
plot(datetime, submetering1, type="scatter", ylab="Energy Submetering", xlab="")
lines(datetime, submetering2, type="scatter", col="red")
lines(datetime, submetering3, type="scatter", col="blue")
legend("topright", c("Sub_metering1", "Submetering2", "Sub_metering3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()
